### ISSUE TITLE
.zeek files are not supported

### ISSUE THREAD

**Issue by 0xekez** [aeppert/bro-vsc-extension#1]
At the moment `.zeek` files aren't highlighted by the extension. This should be a fairly trivial fix. If this is still being maintained I'm happy to make a PR.

**Comment by aeppert** [comment]
Zeke,

Please do. I will happily merge it and get it republished.

Thank you!
Aaron

**Comment by 0xekez** [comment]
Great :)

I might try and get this using the same grammar as the [syntax highlighters](https://github.com/zeek/zeek-sublime/blob/master/Zeek.YAML-tmLanguage) on the Zeek repos as well. Really appreciate you putting this together. Its been really nice to use.
